### ISSUE TITLE
🐛 BUG: Lock command not working.

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#100]

**Comment by thinkverse** [comment]
You're ending the command object on `Line 8`, the command execution isn't on the command object at all.

https://github.com/Heptagram-Bot/Heptagram/blob/c5fc72b8e1927c81aad35938db64d980fcc946ba/commands/Moderation/lock.js#L7-L11

Also, the message event uses `execute` to call each command execution, not `run`.

https://github.com/Heptagram-Bot/Heptagram/blob/c5fc72b8e1927c81aad35938db64d980fcc946ba/events/client/message.js#L11-L13

**Comment by j-dogcoder** [comment]
@thinkverse That is changed on the latest staged commit. It is still broken though

**Comment by thinkverse** [comment]
> @thinkverse That is changed on the latest staged commit. It is still broken though
Ok, I'll pull the latest and check it out.
