### ISSUE TITLE
unlock command

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#102]

**Comment by j-dogcoder** [comment]
.take

**Comment by cemeiq** [comment]
@j-dogcoder Can I take this issue ?

**Comment by j-dogcoder** [comment]
Sure! Use `.take` to claim it. Also, please check out our [CONTRIBUTING.md](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md) before starting.

**Comment by j-dogcoder** [comment]
How's it coming @cemeiq?

**Comment by cemeiq** [comment]
@j-dogcoder Is this unlock command similar to this one [https://github.com/Heptagram-Bot/Heptagram/blob/master/commands/Moderation/lock.js](url). ?

**Comment by j-dogcoder** [comment]
@cemeiq It is the reverse of that.

**Comment by j-dogcoder** [comment]
@cemeiq Put 2 PR's in on your fork

**Comment by cemeiq** [comment]
@j-dogcoder Okay, I will do that. I will get back to this in a day or so.

**Comment by j-dogcoder** [comment]
Ok!

**Comment by cemeiq** [comment]
Hi  @j-dogcoder I will be leaving this issue due to lack of understanding on my part.

**Comment by thinkverse** [comment]
.take

**Comment by j-dogcoder** [comment]
Thank you @thinkverse!
