### ISSUE TITLE
CI and Tests

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#146]

**Comment by gdeep-ciena** [comment]
Interested ,please assign

**Comment by gagandeepp** [comment]
assign this to me

**Comment by gagandeepp** [comment]
Need more details on this

**Comment by j-dogcoder** [comment]
Hey @gagandeepp, basically, we need tests for the bot for when people commit code.

**Comment by Samikmalhotra** [comment]
If you're implementing CI you might need a dockerfile for this, can i add a dockerfile?

**Comment by j-dogcoder** [comment]
Right now I think we just want tests
