### ISSUE TITLE
Guild Only Command Notification

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#169]
message to user if guild only command is ran in dm

**Comment by slayer321** [comment]
Hello @j-dogcoder, I am new to the open-source community. I would like to take up this issue. Please brief me on the issue.

**Comment by j-dogcoder** [comment]
Hey there @slayer321! We would love to have you contribute! Please check out our [contributing guide](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md).

**Comment by j-dogcoder** [comment]
For this issue, Most commands have a property called "guild only". We want users to receive a message when they execute a guild only command in a DM.

**Comment by slayer321** [comment]
Hey, @j-dogcoder  I read [contributing guide](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md) and also forked and done with all the installation and added the token and the bot is up and running. The bot is very Cool I liked it. This is the first time I'm working with the bot's so there are some doubts that I have.
 I check that some bot command has the property `guide only`  which is set to `false`
. From your this [comment](https://github.com/Heptagram-Bot/Heptagram/issues/169#issuecomment-846474379)  I have understood that you want the user to receive the message in their DM whenever they type the command which has the property `guide only` set as `true` is this what you want? like the `!dadJoke` command when the user will execute that command you want that the joke must be received to user's DM right ? and how can it be done?

**Comment by j-dogcoder** [comment]
Hey @slayer321 , you could check out [https://discordjs.guide/command-handling/adding-features.html#guild-only-commands](https://discordjs.guide/command-handling/adding-features.html#guild-only-commands) for some more info.

**Comment by j-dogcoder** [comment]
How's it going @slayer321?

**Comment by slayer321** [comment]
Hey, @j-dogcoder  what I have understood till now is that the command has the property `guild only` that needs to be set as true.
And if the user will try to execute the command which is set as `true`  in anyone's DM then the user will get some message saying `you can't execute this command in DM`, am I right? 
So how can it be implemented .... as I set the `cat` command to true and when I executed in bot's DM the command executed.
I'm confused  😕

**Comment by j-dogcoder** [comment]
Hey @slayer321, you are correct in the basics. The cat command shouldn’t be guild only. Things like kick and ban, however, should be guild only.

**Comment by slayer321** [comment]
the `guide only` property for `ban` and `kick` are already set as true and whenever I'm trying to run that command this is what I'm getting `there was an error trying to execute that command! Please contact a developer in our support server.`
So want to replace this message with some other message which will be sent to the user's DM whenever they are trying to run this command?  this is what you want?

**Comment by j-dogcoder** [comment]
That is correct

**Comment by slayer321** [comment]
ok, so can you give me some reference on how can I implement it .. I searched it but founding nothing useful.
going to sleep will work on it tomorrow.

**Comment by j-dogcoder** [comment]
I suggest you find an issue you know how to work on. If we guided everyone through every issue, that would be all we were doing.
