### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#175]
### Actions to be set up:

- [ ]  https://github.com/actions/stale
- [ ] https://github.com/dessant/lock-threads
- [ ] https://github.com/pascalgn/automerge-action
- [ ]  Some kind of automated release action
- [ ] _more to be added soon..._

**Comment by avinashupadhya99** [comment]
Hey, I'm interested in working on this. Can you please assign this to me? Thanks

**Comment by j-dogcoder** [comment]
Good to have you aboard @avinashupadhya99! Thanks for helping. Please remember to check out our contribution guide. You can also join our community discord.

**Comment by j-dogcoder** [comment]
Does that make sense @avinashupadhya99?

**Comment by avinashupadhya99** [comment]
Hey, what labels do you want to be added? Also, what should be the inactivity period for the stale and thread lock actions?

**Comment by j-dogcoder** [comment]
> Hey, what labels do you want to be added? Also, what should be the inactivity period for the stale and thread lock actions?

Stale should be a month or 2. The lock should be a bit after that. I would also like to be able to mark issues with a "Never Stale" label, that will allow the issues/prs to not become stale.

**Comment by j-dogcoder** [comment]
Any update @avinashupadhya99?

**Comment by j-dogcoder** [comment]
@avinashupadhya99?

**Comment by j-dogcoder** [comment]
Done!
