### ISSUE TITLE
Reaction Roles

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#176]
Maybe using something like [this](https://github.com/NKN1396/Discord-EmojiToRole)?

**Comment by Panquesito7** [comment]
Isn't this already solved?

**Comment by j-dogcoder** [comment]
Not yet!

**Comment by anubhav06** [comment]
Hi, Can I work on this ?

**Comment by MidouWebDev** [comment]
@anubhav06 sure, i am going to assign you !

**Comment by Panquesito7** [comment]
Isn't this already solved?

**Comment by j-dogcoder** [comment]
> Isn't this already solved?
> 
> 

Nope!
