### ISSUE TITLE
🐛 BUG: Unlock command resets to default permissions.

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#187]
The unlock command resets to give everyone full permissions. Can it somehow store the permissions of what the channel had before it was locked?

@thinkverse Maybe you would be willing to take a look at this one?

**Comment by Uklizdev** [comment]
The problem is that when you use `overwritePermissions` in the lock command you are deleting all permissions and only adding the one you want: deny send_messages. So when you unlock it again, you replace all permissions to the defaults and allow send_messages. So twice what you are doing is making all other channel permissions set as default.

What you can do to solve this problem is locking the channel for the role @everyone or for a specific role that can be passed as an argument in the command. If you want me to do that, assign me the  issue and ill do it for you :)

**Comment by j-dogcoder** [comment]
We already have a "User" role to handle mutes. Maybe we can use that as the role to remove permissions from?

**Comment by Uklizdev** [comment]
That'd work but only for your server, not all servers have that User role. How do you wanna implement it? In my opinion its good to leave it to the server admin to decide, if he wants a specific role to be locked from the channel he'd use `!lock <roleID> `or `!unlock <roleID>` . But that's up to you, how do you want them to use the command?

**Comment by j-dogcoder** [comment]
Can it somehow store the permissions of what the channel had before it was locked and then restore it to that?

**Comment by Uklizdev** [comment]
Not that I know of, if you check the TextChannel class in Discord js docs there are 3 methods useful for the lock-unlock purpose: 

- `overwritePermissions` The one you used and deletes the permissions 
- `permissionsFor(memberOrRole) ` This one needs a user id or a role id to work and it returns a "Bitfield" that is, a number that tells you which permissions did that role/user had for that channel. I thought about using this to save the permissions the channel had before using the lock command, but once I have that number, there is no way (I found none) to know which permissions that number is representing, making it useless.
- `updateOverwrite(userOrRole)` Is the one I'm suggesting to use, this one will add or remove a permission for the channel to the specified role/user.

[TextChannel Docs](https://discord.js.org/#/docs/main/stable/class/TextChannel)
[BitField Docs](https://discord.js.org/#/docs/main/stable/class/BitField)


I'm gonna keep searching for ways to get the permissions from the BitField, if it is possible then we should think of a way to store it. I thought of this. When you lock the channel the bot sends a message to the channel saying "Channel locked, case number: BITFIELD NUM" and then require the user to pass that BitField num as a parameter for the Unlock command. Let me know if you have any other ideas in how to make this work.
