### ISSUE TITLE
Inclusive Language Module

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#194]
It would be cool if we could use [alexjs](https://alexjs.com) to make a module that will alert users in chat if they aren't using inclusive language. Of course, if guilds wanted to disable this, It could be disableable per guild.

**Comment by Panquesito7** [comment]
We could do something *similar* to what the [EddieBot](https://github.com/EddieHubCommunity/EddieBot) does: put the blacklisted words in a file and tell the user to edit their message. I could try to work on it if wanted. 🙂

**Comment by j-dogcoder** [comment]
That'd be awesome @Panquesito7! Fun fact, EddieBot uses the same package (alexjs)

**Comment by Panquesito7** [comment]
> That'd be awesome @Panquesito7! Fun fact, EddieBot uses the same package (alexjs)

We could look into how EddieBot uses it (not copy-pasta, just a reference).

**Comment by Vyvy-vi** [comment]
In my opinion, even though Alexjs is a great module, it often mis-performs. We use Alexjs over at EddieHub's discord, and it often doesn't include many words...

After talking to the maintainer, we found out that Alexjs isn't meant for this purpose, and a good way to move forward with inclusivity chat moderation would be to write our own retext plagin...
Would you be interested in a collaborative project?

**Comment by j-dogcoder** [comment]
> In my opinion, even though Alexjs is a great module, it often mis-performs. We use Alexjs over at EddieHub's discord, and it often doesn't include many words...
> 
> After talking to the maintainer, we found out that Alexjs isn't meant for this purpose, and a good way to move forward with inclusivity chat moderation would be to write our own retext plagin... Would you be interested in a collaborative project?

I'd for sure be interested!
