### ISSUE TITLE
Propper mute system

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#214]
Currently, mutes are just role-based, so if a user leaves a server then rejoins, they won't be muted anymore. **This issue will require some database work.**

**Comment by ryguigas0** [comment]
Can you assign this issue to me? Also how can I set the config.json correctly?

**Comment by j-dogcoder** [comment]
Hey @ryguigas0, you can get the config by emailing config.request@heptagram.xyz

**Comment by ryguigas0** [comment]
Already emailed, does it take too long to receive an answer?

**Comment by j-dogcoder** [comment]
Should be in the next hour.
