### ISSUE TITLE
✨❓ Feature Request: Lockdown Command

### ISSUE THREAD

**Issue by net-tech** [Heptagram-Bot/Heptagram#217]
The lockdown command would lock the whole server by changing role perms for `@everyone` role. Now of course it is up to owners to make sure channels perms are set up right too.

**Comment by j-dogcoder** [comment]
The perms would be for the `user` role, as the bot uses roles like user, and muted, to mute users. Other than that, great idea!

**Comment by tommy-lariccia** [comment]
New to github. If someone wants to assign this to me, I'll start working on it and try to make a PR.

**Comment by j-dogcoder** [comment]
All set! Let me know if you need anything, and feel free to join the discord server.

**Comment by net-tech** [comment]
@j-dogcoder Hey any update on this?

**Comment by j-dogcoder** [comment]
👍🏻 Thanks for the heads up @tommy-lariccia
