### ISSUE TITLE
Heptagram Website

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#218]
This is the issue for the Heptagram Website. You can find its repo at [https://github.com/Heptagram-Bot/website](https://github.com/Heptagram-Bot/website).

This issue will be marked as locked, please have any discussion on its repo.

**Comment by MidouWebDev** [comment]
@j-dogcoder I think we can close it, no ?

**Comment by j-dogcoder** [comment]
Correct!
