### ISSUE TITLE
Dynamic Help command rewrite

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#22]
[https://discordjs.guide/command-handling/adding-features.html#a-dynamic-help-command](https://discordjs.guide/command-handling/adding-features.html#a-dynamic-help-command)

**Comment by ceelo777** [comment]
I'd be interested in taking this issue!

**Comment by j-dogcoder** [comment]
All yours! We have some documentation in the readme you should look at before starting.

**Comment by j-dogcoder** [comment]
The article at the top is just a suggestion. You won’t be able to follow it exactly due to the differences in our command handler.

**Comment by j-dogcoder** [comment]
@ceelo777 Let me know if you need anything.

**Comment by Townsy45** [comment]
You would need to update the command handler to be able to support stuff like aliases and categories, or you can look at a command handler that would make this easier.

I have one that is simply to use and will save you some work if you were to look into using one.
https://www.npmjs.com/package/simply-discord
https://github.com/Townsy45/simply-discord

**Comment by j-dogcoder** [comment]
@Townsy45 If you would like to take this on, that would be amazing. Let me know if you are interested and I can assign the issue to you.

**Comment by ceelo777** [comment]
Sounds good! I'll get to work on it - unless @Townsy45 wants to work on it.

**Comment by ceelo777** [comment]
@j-dogcoder I'm completely new to this repo (and a bit new to Discord as well) - I got the project set up and running, but I'm getting this strange error (I'm Administrator btw on my server so I'm confused as to why this is happening)

Bot Ready and Online!
ReferenceError: admin is not defined.

Any ideas?

**Comment by ceelo777** [comment]
Feel free to assign this issue to someone else if I'm too much of a newbie - I'm down to do other issues that are maybe not as complicated perhaps since this project looks very intriguing to me and I'm just looking to contribute in any way I can.

**Comment by j-dogcoder** [comment]
@ceelo777 You have to create a config.json and define the roles that are in there. You can look at the example-config.json for details. Basically, your config.json should look something like this.

`{
  "prefix": "!",
  "token": "your-token-goes-here",
  "roles": {
    "admin": "826438768621910000",
    "users": "826438671993010000",
    "muted": "826438805686050000"
  }
}`

**Comment by j-dogcoder** [comment]
<img width="308" alt="Screen Shot 2021-04-02 at 6 38 56 AM" src="https://user-images.githubusercontent.com/65788728/113408843-1d335d80-937e-11eb-9f93-8dbc53a1bde9.png">
The spacing did not work on that so I took a picture also.

**Comment by j-dogcoder** [comment]
You will need to replace the role ids with ones from your server.

**Comment by j-dogcoder** [comment]
I will let you take this one @ceelo777 . @Townsy45 has commented on other ones also

**Comment by j-dogcoder** [comment]
You will have to replace the values with your own. You can leave the prefix though. The bot token you will have to get from discord's developer portal. You will have to create the 3 roles shown above in your test server

**Comment by j-dogcoder** [comment]
@ceelo777 We now have staff only and bot admin only commands. Can we update the help command again so that those are excluded unless the user has that role?
