### ISSUE TITLE
Proper Bot Logging

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#23]
The idea would be for bot events to be logged in MongoDB, as well as a separate database with logs for every guild.
And then, guild owners can also specify a discord channel they want their guild events logged in. Ideally, we could tap into discord's audit log so heptagram can display events that happened that it didn't do.

**Comment by ting-c** [comment]
Can I take this issue please @j-dogcoder ?

**Comment by j-dogcoder** [comment]
Of course!

**Comment by ting-c** [comment]
Is the purpose of the logging to be saved in a file then stored in the database?

**Comment by j-dogcoder** [comment]
@ting-c The plan was to have a master log(logs actions for all guilds) inside the database and for users to be able to specify a log channel(only logs actions in their guild)

**Comment by j-dogcoder** [comment]
Does that make sense @ting-c?

**Comment by ting-c** [comment]
@j-dogcoder  Yes kind of, may ask for further description if needed.

**Comment by j-dogcoder** [comment]
Let me know if you do.

**Comment by j-dogcoder** [comment]
How's this going @ting-c?

**Comment by j-dogcoder** [comment]
The idea would be for bot events to be logged in MongoDB, as well as a separate database with logs for every guild.
And then, guild owners can also specify a discord channel they want their guild events logged in.

**Comment by j-dogcoder** [comment]
Ideally, we could tap into discord's audit log so heptagram can display events that happened that it didn't do.

**Comment by j-dogcoder** [comment]
Posibly using [https://www.npmjs.com/package/discord-messages](https://www.npmjs.com/package/discord-messages)?

**Comment by ting-c** [comment]
Currently using [https://www.npmjs.com/package/discord-auditlog](https://www.npmjs.com/package/discord-auditlog)

**Comment by j-dogcoder** [comment]
Connected to #242

**Comment by gdeep-ciena** [comment]
Interested,please assign

**Comment by j-dogcoder** [comment]
All yours @gdeep-ciena!

**Comment by gagandeepp** [comment]
@j-dogcoder  This is my personal account. Please assign to this user
