### ISSUE TITLE
Warning for invite

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#231]
Commit [c80286a](https://github.com/Heptagram-Bot/Heptagram/commit/c80286a34c1780aba3ec286660ee699f6edb8aa3) adds support for anti ad (only discord links currently). Once the warnings system is done, we want it to give them a warning when they send a discord link.

**Comment by anubhav06** [comment]
Can you elaborate this a bit ?
Do you want the bot to automatically send the warning or you want users to manually send warning using bot commands

**Comment by j-dogcoder** [comment]
@anubhav06 We want to have the bot to send it.

**Comment by anubhav06** [comment]
This should be database integrated as well, right ? Or just a simple msg

**Comment by j-dogcoder** [comment]
Ideally #86 would also get done, and all of it would be database integrated.

**Comment by anubhav06** [comment]
Ok! I'll work on this

**Comment by j-dogcoder** [comment]
@anubhav06 Want to comment on it so I can assign you to it?
