### ISSUE TITLE
Twitch and Youtube notification abilitys

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#24]
Allows twitch and/or youtube notifications in chat.

**Comment by j-dogcoder** [comment]
It would also be cool if it gave a role called something like "now streaming" to the steamer while they streamed and then took it away when they were done.

**Comment by RattaphonKarnsomlap** [comment]
Gh

**Comment by j-dogcoder** [comment]
> Gh

?

**Comment by j-dogcoder** [comment]
@RattaphonKarnsomlap What do you mean?

**Comment by j-dogcoder** [comment]
Everyone should check out FiniteSingularity's [TAU](https://github.com/FiniteSingularity/tau/). TAU is basically a tool for interacting with the Twitch API. (Possible plans for youtube API later). The plan is for TAU to be baked in as our stream notification system.

**Comment by j-dogcoder** [comment]
Please make sure to check out the issue in the TAU repo seeing as it pertains some good ideas.
