### ISSUE TITLE
✨❓ Feature Request: Clyde messages via Webhooks

### ISSUE THREAD

**Issue by Vyvy-vi** [Heptagram-Bot/Heptagram#241]
## **Description**

The bot currently outputs an image with text added on it, however this isn't a very optimal solution(unless we set up logic to resize the template message image to whatever length the command message uses). Moreover, the bot doesn't support channel tagging or pinging people. Instead of rendering an image, we could just create a webhook to that channel, and send the message via the webhook(*this way it would look like a fake Clyde)

## **Images**

![Screenshot 2021-07-23 at 10 05 20 PM](https://user-images.githubusercontent.com/62864373/126813630-f7eea920-a68a-47ef-ae0a-43969cfb120a.png)

## [Optional] **Additional Context**:

Follows up on the [conversation on the discord server](https://discord.com/channels/826493837878493204/826590484389560390/868165399101968414)

You can also join the discord community [here](https://discord.com/invite/HSupF99kpq)

**Comment by Vyvy-vi** [comment]
I'm wondering if this would be of much utility if we can't have "Clyde" in the webhook's name.
Perhaps we can either implement this in the API(*might be some heavy image editing, if we want it to work flawlessly but I think it's doable) OR we rename the webhook name, and call it something like "Discord System".

Also, adding this might also cause issues with the anti-link workflow. (there were a few errors due to the use of webhooks)

**Comment by j-dogcoder** [comment]
Hey @Vyvy-vi, I have implemented a fix for the anti-link workflow, I think it would be better if we implement in API.
