### ISSUE TITLE
Heptagram Log and Error Handler

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#242]
Based on [https://github.com/BeccaLyria/discord-bot/blob/main/src/utils/beccaErrorHandler.ts](https://github.com/BeccaLyria/discord-bot/blob/main/src/utils/beccaErrorHandler.ts)
and
[https://github.com/BeccaLyria/discord-bot/blob/main/src/utils/beccaLogHandler.ts](https://github.com/BeccaLyria/discord-bot/blob/main/src/utils/beccaLogHandler.ts)

Implement using WOKCommads error things. [https://docs.wornoffkeys.com/commands/handling-command-errors](https://docs.wornoffkeys.com/commands/handling-command-errors)

**Comment by j-dogcoder** [comment]
Duplicate of #23

**Comment by prithvijit-dasgupta** [comment]
@j-dogcoder `winston` is a dead library (although very popular). The last commit was in 2020. It would be better to go ahead with a maintained logger library like [pino](https://github.com/pinojs/pino)

**Comment by j-dogcoder** [comment]
Totally fine using just about anything. Would like to do something connected to the first message for sure though. Want to take this issue @prithvijit-dasgupta?

**Comment by prithvijit-dasgupta** [comment]
So I only see a couple of logs in the bot server. The expectation is to set up a logging and error framework right? 
I am very new to the Discord bot APIs but I am interested in learning and developing this

**Comment by prithvijit-dasgupta** [comment]
Also is there a place with the schema and example data for the `config.json` file? I am unable to start the server without it

**Comment by j-dogcoder** [comment]
That is the premise yes. We want a log and error handler based on `https://github.com/BeccaLyria/discord-bot/blob/main/src/utils/beccaErrorHandler.ts` and `https://github.com/BeccaLyria/discord-bot/blob/main/src/utils/beccaLogHandler.ts`. That bot stuff is written in typescript, so we want to replicate that as much as possible in js. It would also be nice to have permanent logs in somewhere like a database also. In terms of the config, if you have discord you can join our server there, or alternatively you can send me an email at j.dogcoder@heptagram.xyz and I can email you it. Let me know what you want to do.

**Comment by j-dogcoder** [comment]
Sound good @prithvijit-dasgupta?

**Comment by j-dogcoder** [comment]
Would you like to work on this?

**Comment by prithvijit-dasgupta** [comment]
Yeah. I will work on this over the weekend

**Comment by j-dogcoder** [comment]
Any progress update @prithvijit-dasgupta?
