### ISSUE TITLE
Prefix mention not working

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#255]

**Comment by jehincastic** [comment]
Hey @j-dogcoder I would like to work on this issue.

Could you please elaborate a little so that it would be useful.

**Comment by j-dogcoder** [comment]
Hey @jehincastic! The bot is supposed to reply when mentioned to, but right now it replies with 

`Hey there! Need some help? My commands can be accessed through my prefix. My prefix in this server is [object Object]. You can use **[object Object]help for a list of all my commands.`

See the issue? object Object should be the prefix.
