### ISSUE TITLE
✨❓ Feature Request: Make the bot multilingual

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot/Heptagram#268]
**Description**

I see that the bot should be multilingual so that everyone can use it. I worked on the french translation and i am going to start working on the arabic translation.
So please, if you want to translate the bot to your language, comment below.
Thanks

**Comment by MidouWebDev** [comment]
@j-dogcoder i suggest to keep this feature for the v2.0

**Comment by j-dogcoder** [comment]
The bot already supports this @MidouWebDev

**Comment by MidouWebDev** [comment]
Ok
