### ISSUE TITLE
✨❓ Create a command that takes a word and return the meaning of the word

### ISSUE THREAD

**Issue by akzain** [Heptagram-Bot/Heptagram#277]
**Description**

A new cool feature for the heptagram bot will be that we should create a command that accepts a word and then it returns the meaning of the word

**Comment by pomf1** [comment]
Hey, I left you a <strong>PR</strong> with the command you asked for! https://github.com/Heptagram-Bot/Heptagram/pull/279

Greetings! ♥

**Comment by j-dogcoder** [comment]
Thanks! I'll take a look tomorrow.
