### ISSUE TITLE
✨❓ Feature Request: Use CodeQL instead of LGTM

### ISSUE THREAD

**Issue by Panquesito7** [Heptagram-Bot/Heptagram#291]
**Description**

We should use [CodeQL](https://github.com/github/codeql) instead of [LGTM](https://lgtm.com), as [CodeQL](https://github.com/github/codeql) is faster.

[Optional] **Additional Context**

[LGTM](https://lgtm.com) is a nice scanning tool. [CodeQL](https://github.com/github/codeql) is what powers [LGTM](https://lgtm.com). However, [LGTM](https://lgtm.com) takes too long to check for new/fixed alerts. [CodeQL](https://github.com/github/codeql) **works much more [faster](https://github.com/TheAlgorithms/website/pull/24)**, and [LGTM](https://lgtm.com) seems to only use [CodeQL](https://github.com/github/codeql). You can also see [CodeQL](https://github.com/github/codeql) runs on commits, and [LGTM](https://lgtm.com) doesn't.

**Comment by j-dogcoder** [comment]
Want to implement this?

**Comment by j-dogcoder** [comment]
@Panquesito7

**Comment by Panquesito7** [comment]
Sure, I'll create a PR for it; thanks. 🙂

**Comment by Panquesito7** [comment]
This should be in `master` already. Closing.
