### ISSUE TITLE
✨❓ Feature Request: A better idea for the Command Handler Packager

### ISSUE THREAD

**Issue by Panquesito7** [Heptagram-Bot/Heptagram#292]
**Description**

The current idea of the Command Handler Packager is to use somewhat of an API to register commands.
I suggest we should simply use the Discord.js API to implement those commands without the need for any APIs.

_Offtopic:_ I can also work on the slash commands if wanted.

[Optional] **Additional Context**

I don't think there's a need for any additional context. If you need more information, though, let me know. Thanks. 🙂

**Comment by j-dogcoder** [comment]
I'm not sure your understanding how discord bots work. We use a library called discord.js to interact with the Discord API. Our command handler, is what what makes the bot register commands.
