### ISSUE TITLE
Database Storage

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#3]
Using database for storing things like user role id's and more.

Using 
[https://discordjs.guide/sequelize/#installing-and-using-sequelize](https://discordjs.guide/sequelize/#installing-and-using-sequelize)
or
https://discordjs.guide/keyv/

**Comment by j-dogcoder** [comment]
To clarify, the database would be used so that each server can specify their role ids for admin, user, muted, etc. This would also mean they could set a custom prefix and custom reaction roles.

**Comment by j-dogcoder** [comment]
I have not implemented anything in terms of a database, so this would be a pretty big task.

**Comment by bdougie** [comment]
Where is the bot deployed to? That may influence the answer.

**Comment by j-dogcoder** [comment]
@bdougie The bot is currently just running on my desktop computer. I have some other projects that are going to be resource intensive as well, so I am currently server shopping for a server to be networked at my home/office. Eventually the goal is to run it on that.

**Comment by Townsy45** [comment]
I recommend taking a look at Postgres, if you are looking into an SQL variant. Its powerful and easy to use / install. 
I use it for all of my projects, both Discord related and non.

Official page: [postgresql.org](https://www.postgresql.org/)

Great place to learn syntax and general tutorials: [www.postgresqltutorial.com](https://www.postgresqltutorial.com/what-is-postgresql/)

**Comment by j-dogcoder** [comment]
@Townsy45 If you would like to take this on, that would be amazing.

**Comment by j-dogcoder** [comment]
Let me know and I can assign it to you.

**Comment by LejhandGamingYT** [comment]
I can help you out..... 👀👀

**Comment by j-dogcoder** [comment]
Part of #103
