### ISSUE TITLE
web dashboard

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#30]
a web interface for changing bot configs and settings.

**Comment by j-dogcoder** [comment]
Looks like [https://github.com/IgorKowalczyk/majobot](https://github.com/IgorKowalczyk/majobot) has a interesting dashboard

**Comment by j-dogcoder** [comment]
Maybe using something like [https://github.com/julianYaman/discord-bot-dashboard](https://github.com/julianYaman/discord-bot-dashboard)?

**Comment by j-dogcoder** [comment]
I definitely want something for ban appeals like [https://github.com/jcsumlin/discord-ban-appeal](https://github.com/jcsumlin/discord-ban-appeal)

**Comment by MidouWebDev** [comment]
@j-dogcoder , can i know what was about ?

**Comment by j-dogcoder** [comment]
This issues is moved to the website repo
