### ISSUE TITLE
ModMail/Ticketing feature

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#31]
If https://github.com/Dragory/modmailbot and https://ticketsbot.net/ had a child.

**Comment by j-dogcoder** [comment]
Could be cool to implement [https://github.com/ghoststools/djs-ticketsystem](https://github.com/ghoststools/djs-ticketsystem)

**Comment by j-dogcoder** [comment]
[https://www.youtube.com/watch?v=hYfcycOI9BY&list=PLaxxQQak6D_fxb9_-YsmRwxfw5PH9xALe&index=30](https://www.youtube.com/watch?v=hYfcycOI9BY&list=PLaxxQQak6D_fxb9_-YsmRwxfw5PH9xALe&index=30)

**Comment by MidouWebDev** [comment]
@j-dogcoder we are not going to have this feature ?

**Comment by j-dogcoder** [comment]
Not currently
