### ISSUE TITLE
[FEAT] - Add an anti-swear system

### ISSUE THREAD

**Issue by Panquesito7** [Heptagram-Bot/Heptagram#316]
### What feature would you like to see?

Add an anti-swear system. We can use the [`leo-profanity`](https://github.com/jojoee/leo-profanity) library for that. It works very well with a lot of words and it doesn't get confused with stuff like `assignment`, which *could* get blocked for the first three letters.

### Additional information

I don't think so.

**Comment by j-dogcoder** [comment]
Want to work on this @Panquesito7?

**Comment by j-dogcoder** [comment]
Sort of relates to #194 and #315

**Comment by Panquesito7** [comment]
> Want to work on this @Panquesito7?

Sure! I'll try to work on it these days. Thanks. 😄
