### ISSUE TITLE
[BUG] - "Utilitys" instead of "Utilities"

### ISSUE THREAD

**Issue by Xico26** [Heptagram-Bot/Heptagram#318]
### What bug did you encounter?

On of the options on the help command (!help) is "Utilitys"

### What did you expect to happen?

It should be "Utilities" 

### Screenshots

![image](https://user-images.githubusercontent.com/47830278/134934058-61c62326-05a6-4234-8990-ac7f8eaf6f13.png)

**Comment by j-dogcoder** [comment]
Hey @Xico26! Thanks for submitting this! Want to work on this? If not, we can have someone else do it.

**Comment by MidouWebDev** [comment]
@j-dogcoder i can work on it if he doesn't want to.
