### ISSUE TITLE
[OTHER] - Missing yarn.lock file

### ISSUE THREAD

**Issue by monzilnepali** [Heptagram-Bot/Heptagram#323]
### What would you like to share?

I noticed that `yarn.lock `is missing from the repo; I'm not sure if this is intentional or not. However, I believe it is critical that `yarn.lock` be pushed to the repo so that everyone has the same package version.

### Additional information

https://classic.yarnpkg.com/en/docs/yarn-lock/
https://nodejs.dev/learn/the-package-lock-json-file

**Comment by Panquesito7** [comment]
I think we're using `package.json` here, which means we're using NPM, so I don't see a need for Yarn. Let's wait until @j-dogcoder answers and see what they say. 🙂

**Comment by monzilnepali** [comment]
@Panquesito7 I am referring `yarn.lock` file based on [installing-depdencies](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md#installing-dependencies)

**Comment by Panquesito7** [comment]
> @Panquesito7 I am referring `yarn.lock` file based on [installing-depdencies](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md#installing-dependencies)

Ahh, I see 😅 my bad, sorry.

**Comment by j-dogcoder** [comment]
Closed by 1a8cfd2acc175193ffa372e6160ea6b0ca3ef0e6
