### ISSUE TITLE
[OTHER] - Setup prettier with eslint

### ISSUE THREAD

**Issue by monzilnepali** [Heptagram-Bot/Heptagram#324]
### What would you like to share?

This issue is regarding setting up `prettier` and integrates with `eslint` so that all developers will have the same formatting configuration.

### Additional information
https://blog.theodo.com/2019/08/empower-your-dev-environment-with-eslint-prettier-and-editorconfig-with-no-conflicts
https://prettier.io/docs/en/integrating-with-linters.html

**Comment by monzilnepali** [comment]
@j-dogcoder lemme know if you need any help on this

**Comment by j-dogcoder** [comment]
Hey @monzilnepali, If you'd like to work on this, you are welcome to!

**Comment by monzilnepali** [comment]
@j-dogcoder Sure I can take this one

**Comment by MidouWebDev** [comment]
@monzilnepali i assigned you
