### ISSUE TITLE
BUG: ticket.js perms

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#43]
This Bug has several things that need to be fixed

- [ ] Change channel.setParent's value in ticket.js on line 6 to a value in the config.json file 
- [ ] switch perm on line 28 to a hardcoded value in the config.json

**Comment by j-dogcoder** [comment]
Also add error message if user uses reactions

**Comment by j-dogcoder** [comment]
Related to issue #31

**Comment by ceelo777** [comment]
I'll take this issue!

**Comment by j-dogcoder** [comment]
Go for it @ceelo777 ! Check your discord messages first though pls
