### ISSUE TITLE
Music Bot

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#48]

**Comment by ceelo777** [comment]
I'll take this issue!

**Comment by j-dogcoder** [comment]
Great @ceelo777!

**Comment by j-dogcoder** [comment]
How's this going @ceelo777?

**Comment by ceelo777** [comment]
Still working on it - going to take a bit of time to get all the commands working and whatnot.

**Comment by j-dogcoder** [comment]
Ok!

**Comment by Mert18** [comment]
.take I am working on it :)

**Comment by j-dogcoder** [comment]
Yay! Thanks @Mert18!
